<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConnectionTableSeeder extends Seeder
{
    public function run(): void
    {
        $connections = [
            ['name' => 'Telegram'],
            ['name' => 'YouTube'],
            ['name' => 'Facebook'],
            ['name' => 'Instagram'],
            ['name' => 'TikTok'],
            ['name' => 'Website'],
            ['name' => 'Email'],
            ['name' => 'Phone'],
            ['name' => 'Github'],
            ['name' => 'LinkedIn'],
            ['name' => 'Twitter'],
            ['name' => 'WhatsApp'],
            ['name' => 'Viber'],
            ['name' => 'Snapchat'],
            ['name' => 'Pinterest'],
            ['name' => 'Reddit'],
            ['name' => 'Tumblr'],
            ['name' => 'Flickr'],
            ['name' => 'Medium'],
            ['name' => 'Quora'],
            ['name' => 'WeChat'],
            ['name' => 'Line'],
            ['name' => 'VK'],
            ['name' => 'Odnoklassniki'],
            ['name' => 'Yelp'],
            ['name' => 'Zalo'],
            ['name' => 'Discord'],
            ['name' => 'Skype'],
            ['name' => 'Zoom'],
            ['name' => 'Microsoft Teams'],
            ['name' => 'Slack'],
            ['name' => 'Google Meet'],
            ['name' => 'Signal'],
            ['name' => 'Threema'],
            ['name' => 'Wire'],
            ['name' => 'Keybase'],
            ['name' => 'Telegram Business'],
            ['name' => 'WhatsApp Business'],
            ['name' => 'Facebook Messenger'],
            ['name' => 'Google Chat'],
            ['name' => 'Apple FaceTime'],
            ['name' => 'Viber Business'],
            ['name' => 'WeChat Work'],
            ['name' => 'KakaoTalk'],
            ['name' => 'Naver Line'],
            ['name' => 'Rakuten Viber'],
            ['name' => 'IMO'],
            ['name' => 'Chatwork'],
            ['name' => 'Flock'],
            ['name' => 'Mattermost'],
            ['name' => 'Rocket.Chat'],
            ['name' => 'Zulip'],
            ['name' => 'Element'],
            ['name' => 'Matrix'],
            ['name' => 'Jitsi'],
            ['name' => 'BigBlueButton'],
            ['name' => 'Whereby'],
            ['name' => 'GoToMeeting'],
            ['name' => 'Webex'],
            ['name' => 'BlueJeans'],
            ['name' => 'Join.me'],
            ['name' => 'AnyMeeting'],
            ['name' => 'FreeConferenceCall.com'],
            ['name' => 'UberConference'],
            ['name' => 'Dialpad'],
            ['name' => 'RingCentral'],
            ['name' => '8x8'],
            ['name' => 'Vonage'],
            ['name' => 'Twilio'],
            ['name' => 'Plivo'],
            ['name' => 'MessageBird'],
            ['name' => 'Sinch'],
            ['name' => 'Clickatell'],
            ['name' => 'Infobip'],
            ['name' => 'Telesign'],
            ['name' => 'Vonage API'],
            ['name' => 'Bandwidth'],
            ['name' => 'Telnyx'],
            ['name' => 'AWS SNS'],
            ['name' => 'Azure Communication Services'],
            ['name' => 'Google Cloud Pub/Sub'],
            ['name' => 'Firebase Cloud Messaging'],
            ['name' => 'Apple Push Notification Service'],
            ['name' => 'OneSignal'],
            ['name' => 'Pusher'],
            ['name' => 'PubNub'],
            ['name' => 'Ably'],
            ['name' => 'Socket.io'],
            ['name' => 'WebSocket'],
            ['name' => 'WebRTC'],
            ['name' => 'SIP'],
            ['name' => 'H.323'],
            ['name' => 'MGCP'],
            ['name' => 'SCCP'],
            ['name' => 'IAX'],
            ['name' => 'RTP'],
            ['name' => 'SRTP'],
            ['name' => 'DTLS'],
            ['name' => 'STUN'],
            ['name' => 'TURN'],
            ['name' => 'ICE'],
            ['name' => 'SIP-T'],
            ['name' => 'SIP-I'],
            ['name' => 'H.248'],
            ['name' => 'MEGACO'],
            ['name' => 'SIGTRAN'],
            ['name' => 'SS7'],
            ['name' => 'ISDN'],
            ['name' => 'PSTN'],
            ['name' => 'GSM'],
            ['name' => 'CDMA'],
            ['name' => 'LTE'],
            ['name' => '5G'],
            ['name' => 'VoIP'],
            ['name' => 'VoLTE'],
            ['name' => 'VoWiFi'],
            ['name' => 'RCS'],
            ['name' => 'SMS'],
            ['name' => 'MMS'],
            ['name' => 'USSD'],
            ['name' => 'WAP Push'],
            ['name' => 'CB'],
            ['name' => 'Cell Broadcast'],
        ];

        DB::table('connection')->insert($connections);
    }
}
