<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConnectionTableSeeder extends Seeder
{
    public function run(): void
    {
        $connections = [
            ['name' => 'Telegram', 'icon' => 'fab fa-telegram'],
            ['name' => 'YouTube', 'icon' => 'fab fa-youtube'],
            ['name' => 'Facebook', 'icon' => 'fab fa-facebook'],
            ['name' => 'Instagram', 'icon' => 'fab fa-instagram'],
            ['name' => 'TikTok', 'icon' => 'fab fa-tiktok'],
            ['name' => 'Website', 'icon' => 'fas fa-globe'],
            ['name' => 'Email', 'icon' => 'fas fa-envelope'],
            ['name' => 'Phone', 'icon' => 'fas fa-phone'],
            ['name' => 'Github', 'icon' => 'fab fa-github'],
            ['name' => 'LinkedIn', 'icon' => 'fab fa-linkedin'],
            ['name' => 'Twitter', 'icon' => 'fab fa-twitter'],
            ['name' => 'WhatsApp', 'icon' => 'fab fa-whatsapp'],
            ['name' => 'Viber', 'icon' => 'fab fa-viber'],
            ['name' => 'Snapchat', 'icon' => 'fab fa-snapchat'],
            ['name' => 'Pinterest', 'icon' => 'fab fa-pinterest'],
            ['name' => 'Reddit', 'icon' => 'fab fa-reddit'],
            ['name' => 'Tumblr', 'icon' => 'fab fa-tumblr'],
            ['name' => 'Flickr', 'icon' => 'fab fa-flickr'],
            ['name' => 'Medium', 'icon' => 'fab fa-medium'],
            ['name' => 'Quora', 'icon' => 'fab fa-quora'],
            ['name' => 'WeChat', 'icon' => 'fab fa-weixin'],
            ['name' => 'Line', 'icon' => 'fab fa-line'],
            ['name' => 'VK', 'icon' => 'fab fa-vk'],
            ['name' => 'Odnoklassniki', 'icon' => 'fab fa-odnoklassniki'],
            ['name' => 'Yelp', 'icon' => 'fab fa-yelp'],
            ['name' => 'Zalo', 'icon' => 'fas fa-comment'],
            ['name' => 'Discord', 'icon' => 'fab fa-discord'],
            ['name' => 'Skype', 'icon' => 'fab fa-skype'],
            ['name' => 'Zoom', 'icon' => 'fas fa-video'],
            ['name' => 'Microsoft Teams', 'icon' => 'fab fa-microsoft'],
            ['name' => 'Slack', 'icon' => 'fab fa-slack'],
            ['name' => 'Google Meet', 'icon' => 'fab fa-google'],
            ['name' => 'Signal', 'icon' => 'fas fa-signal'],
            ['name' => 'Threema', 'icon' => 'fas fa-shield-alt'],
            ['name' => 'Wire', 'icon' => 'fas fa-wifi'],
            ['name' => 'Keybase', 'icon' => 'fas fa-key'],
            ['name' => 'Telegram Business', 'icon' => 'fab fa-telegram'],
            ['name' => 'WhatsApp Business', 'icon' => 'fab fa-whatsapp'],
            ['name' => 'Facebook Messenger', 'icon' => 'fab fa-facebook-messenger'],
            ['name' => 'Google Chat', 'icon' => 'fab fa-google'],
            ['name' => 'Apple FaceTime', 'icon' => 'fab fa-apple'],
            ['name' => 'Viber Business', 'icon' => 'fab fa-viber'],
            ['name' => 'WeChat Work', 'icon' => 'fab fa-weixin'],
            ['name' => 'KakaoTalk', 'icon' => 'fas fa-comment'],
            ['name' => 'Naver Line', 'icon' => 'fab fa-line'],
            ['name' => 'Rakuten Viber', 'icon' => 'fab fa-viber'],
            ['name' => 'IMO', 'icon' => 'fas fa-comment'],
            ['name' => 'Chatwork', 'icon' => 'fas fa-comments'],
            ['name' => 'Flock', 'icon' => 'fas fa-comments'],
            ['name' => 'Mattermost', 'icon' => 'fas fa-comments'],
            ['name' => 'Rocket.Chat', 'icon' => 'fas fa-rocket'],
            ['name' => 'Zulip', 'icon' => 'fas fa-comment'],
            ['name' => 'Element', 'icon' => 'fas fa-comment'],
            ['name' => 'Matrix', 'icon' => 'fas fa-th'],
            ['name' => 'Jitsi', 'icon' => 'fas fa-video'],
            ['name' => 'BigBlueButton', 'icon' => 'fas fa-chalkboard'],
            ['name' => 'Whereby', 'icon' => 'fas fa-video'],
            ['name' => 'GoToMeeting', 'icon' => 'fas fa-video'],
            ['name' => 'Webex', 'icon' => 'fas fa-video'],
            ['name' => 'BlueJeans', 'icon' => 'fas fa-video'],
            ['name' => 'Join.me', 'icon' => 'fas fa-video'],
            ['name' => 'AnyMeeting', 'icon' => 'fas fa-video'],
            ['name' => 'FreeConferenceCall.com', 'icon' => 'fas fa-phone'],
            ['name' => 'UberConference', 'icon' => 'fas fa-phone'],
            ['name' => 'Dialpad', 'icon' => 'fas fa-phone'],
            ['name' => 'RingCentral', 'icon' => 'fas fa-phone'],
            ['name' => '8x8', 'icon' => 'fas fa-phone'],
            ['name' => 'Vonage', 'icon' => 'fas fa-phone'],
            ['name' => 'Twilio', 'icon' => 'fas fa-phone'],
            ['name' => 'Plivo', 'icon' => 'fas fa-phone'],
            ['name' => 'MessageBird', 'icon' => 'fas fa-dove'],
            ['name' => 'Sinch', 'icon' => 'fas fa-comment'],
            ['name' => 'Clickatell', 'icon' => 'fas fa-comment'],
            ['name' => 'Infobip', 'icon' => 'fas fa-comment'],
            ['name' => 'Telesign', 'icon' => 'fas fa-phone'],
            ['name' => 'Vonage API', 'icon' => 'fas fa-code'],
            ['name' => 'Bandwidth', 'icon' => 'fas fa-signal'],
            ['name' => 'Telnyx', 'icon' => 'fas fa-phone'],
            ['name' => 'AWS SNS', 'icon' => 'fab fa-aws'],
            ['name' => 'Azure Communication Services', 'icon' => 'fab fa-microsoft'],
            ['name' => 'Google Cloud Pub/Sub', 'icon' => 'fab fa-google'],
            ['name' => 'Firebase Cloud Messaging', 'icon' => 'fas fa-fire'],
            ['name' => 'Apple Push Notification Service', 'icon' => 'fab fa-apple'],
            ['name' => 'OneSignal', 'icon' => 'fas fa-bell'],
            ['name' => 'Pusher', 'icon' => 'fas fa-broadcast-tower'],
            ['name' => 'PubNub', 'icon' => 'fas fa-satellite-dish'],
            ['name' => 'Ably', 'icon' => 'fas fa-broadcast-tower'],
            ['name' => 'Socket.io', 'icon' => 'fas fa-plug'],
            ['name' => 'WebSocket', 'icon' => 'fas fa-link'],
            ['name' => 'WebRTC', 'icon' => 'fas fa-video'],
            ['name' => 'SIP', 'icon' => 'fas fa-phone'],
            ['name' => 'H.323', 'icon' => 'fas fa-video'],
            ['name' => 'MGCP', 'icon' => 'fas fa-phone'],
            ['name' => 'SCCP', 'icon' => 'fas fa-phone'],
            ['name' => 'IAX', 'icon' => 'fas fa-phone'],
            ['name' => 'RTP', 'icon' => 'fas fa-exchange-alt'],
            ['name' => 'SRTP', 'icon' => 'fas fa-lock'],
            ['name' => 'DTLS', 'icon' => 'fas fa-lock'],
            ['name' => 'STUN', 'icon' => 'fas fa-satellite-dish'],
            ['name' => 'TURN', 'icon' => 'fas fa-sync'],
            ['name' => 'ICE', 'icon' => 'fas fa-cube'],
            ['name' => 'SIP-T', 'icon' => 'fas fa-phone'],
            ['name' => 'SIP-I', 'icon' => 'fas fa-phone'],
            ['name' => 'H.248', 'icon' => 'fas fa-video'],
            ['name' => 'MEGACO', 'icon' => 'fas fa-server'],
            ['name' => 'SIGTRAN', 'icon' => 'fas fa-exchange-alt'],
            ['name' => 'SS7', 'icon' => 'fas fa-network-wired'],
            ['name' => 'ISDN', 'icon' => 'fas fa-phone'],
            ['name' => 'PSTN', 'icon' => 'fas fa-phone'],
            ['name' => 'GSM', 'icon' => 'fas fa-signal'],
            ['name' => 'CDMA', 'icon' => 'fas fa-signal'],
            ['name' => 'LTE', 'icon' => 'fas fa-broadcast-tower'],
            ['name' => '5G', 'icon' => 'fas fa-broadcast-tower'],
            ['name' => 'VoIP', 'icon' => 'fas fa-phone'],
            ['name' => 'VoLTE', 'icon' => 'fas fa-phone'],
            ['name' => 'VoWiFi', 'icon' => 'fas fa-wifi'],
            ['name' => 'RCS', 'icon' => 'fas fa-comment'],
            ['name' => 'SMS', 'icon' => 'fas fa-sms'],
            ['name' => 'MMS', 'icon' => 'fas fa-image'],
            ['name' => 'USSD', 'icon' => 'fas fa-mobile-alt'],
            ['name' => 'WAP Push', 'icon' => 'fas fa-mobile'],
            ['name' => 'CB', 'icon' => 'fas fa-broadcast-tower'],
            ['name' => 'Cell Broadcast', 'icon' => 'fas fa-broadcast-tower'],
        ];

        DB::table('connection')->insert($connections);
    }
}
